spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: prabhavsingh404@gmail.com
    password: sotc unch kjqd sztb
    properties:
      mail:
        smtp:
          auth: true
          #(start transport layer security)
          starttls:
            enable: true

logging:
  level:
    com:
      prabhav:
        myJournalApp: TRACE

#logging:
#  level:
#    root: OFF

weather:
  api:
    key: 9afc859359cb3aba97514e067c616830