spring:
  profiles:
    active: dev

logging:
  level:
    com:
      prabhav:
        myJournalApp: TRACE

#logging:
#  level:
#    root: OFF

weather:
  api:
    key: 9afc859359cb3aba97514e067c616830