spring:
  kafka:
    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.prabhav.myJournalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='DRG4WSYAQJJTDPTO' password='cfltVZqPVo9LiAQYteY+BwQ4+ZS7ExDMEgWJZOLW57tv0/LSC2FGCSGtbUXZ/9AA';"
      session:
        timeout:
          ms: 45000
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: prabhavsingh404@gmail.com
    password: sotc unch kjqd sztb
    properties:
      mail:
        smtp:
          auth: true
          #(start transport layer security)
          starttls:
            enable: true

logging:
  level:
    com:
      prabhav:
        myJournalApp: TRACE

#logging:
#  level:
#    root: OFF

weather:
  api:
    key: 9afc859359cb3aba97514e067c616830